/* Audit trail for important actions (who, what, on what, when).
   Written inside the same transaction as the change it records. */
import { newId } from "./tokens.js";

export const ACTIONS = {
  APPLICATION_SUBMITTED: "APPLICATION_SUBMITTED",
  APPLICATION_UNDER_REVIEW: "APPLICATION_UNDER_REVIEW",
  APPLICATION_REJECTED: "APPLICATION_REJECTED",
  SHOP_APPROVED: "SHOP_APPROVED",
  SHOP_CREATED: "SHOP_CREATED",
  SHOP_REJECTED: "SHOP_REJECTED",
  SHOP_UPDATED: "SHOP_UPDATED",
  SHOP_ACTIVATED: "SHOP_ACTIVATED",
  SHOP_DEACTIVATED: "SHOP_DEACTIVATED",
  SHOP_ACCOUNT_CREATED: "SHOP_ACCOUNT_CREATED",
  SHOP_CREDENTIALS_ISSUED: "SHOP_CREDENTIALS_ISSUED",
  SHOP_ACCOUNT_DISABLED: "SHOP_ACCOUNT_DISABLED",
  SHOP_ACCOUNT_ENABLED: "SHOP_ACCOUNT_ENABLED",
  SHOP_PROFILE_UPDATED: "SHOP_PROFILE_UPDATED",
  PASSWORD_RESET: "PASSWORD_RESET",
  ACCOUNT_SETUP_COMPLETED: "ACCOUNT_SETUP_COMPLETED",
  ORDER_STATUS_CHANGED: "ORDER_STATUS_CHANGED",
  ORDER_CANCELLED: "ORDER_CANCELLED",
  ORDER_REFUNDED: "ORDER_REFUNDED",
  ORDER_PHOTO_ACCESSED: "ORDER_PHOTO_ACCESSED",
  ORDER_TEST_LABEL_CHANGED: "ORDER_TEST_LABEL_CHANGED",
  CUSTOMER_RECORD_VIEWED: "CUSTOMER_RECORD_VIEWED",
  ORDER_ITEM_FULFILMENT_CHANGED: "ORDER_ITEM_FULFILMENT_CHANGED",
  SHOP_PRODUCT_SAVED: "SHOP_PRODUCT_SAVED",
  SHOP_PRODUCT_DELETED: "SHOP_PRODUCT_DELETED",
  PRODUCT_MODERATED: "PRODUCT_MODERATED",
  SETTINGS_CHANGED: "SETTINGS_CHANGED",
  USER_STATUS_CHANGED: "USER_STATUS_CHANGED",
  ARTIST_APPLICATION_SUBMITTED: "ARTIST_APPLICATION_SUBMITTED",
  ARTIST_APPLICATION_REJECTED: "ARTIST_APPLICATION_REJECTED",
  ARTIST_APPROVED: "ARTIST_APPROVED",
  ARTIST_CREATED: "ARTIST_CREATED",
  ARTIST_UPDATED: "ARTIST_UPDATED",
  ARTIST_STATUS_CHANGED: "ARTIST_STATUS_CHANGED",
  ARTIST_ACCOUNT_CREATED: "ARTIST_ACCOUNT_CREATED",
  ARTIST_PROFILE_UPDATED: "ARTIST_PROFILE_UPDATED",
  ARTWORK_SUBMITTED: "ARTWORK_SUBMITTED",
  ARTWORK_APPROVED: "ARTWORK_APPROVED",
  ARTWORK_REJECTED: "ARTWORK_REJECTED",
  ARTWORK_STATUS_CHANGED: "ARTWORK_STATUS_CHANGED",
  PAINTING_SERVICE_SAVED: "PAINTING_SERVICE_SAVED",
  PAINTING_REQUESTED: "PAINTING_REQUESTED",
  PAINTING_ACCEPTED: "PAINTING_ACCEPTED",
  PAINTING_DECLINED: "PAINTING_DECLINED",
  PAINTING_STATUS_CHANGED: "PAINTING_STATUS_CHANGED",
  PAINTING_CANCELLED: "PAINTING_CANCELLED",
  PAINTING_PAYMENT_VERIFIED: "PAINTING_PAYMENT_VERIFIED",
  PAINTING_REFERENCE_ACCESSED: "PAINTING_REFERENCE_ACCESSED",
  PAINTING_REFUND_RECORDED: "PAINTING_REFUND_RECORDED",
  REVIEW_MODERATED: "REVIEW_MODERATED"
};

/** q is db or a transaction; actor is req.auth.user (or null for system / public actions). */
export function audit(q, { actor = null, action, targetType, targetId = null, metadata = {}, ip = null }) {
  return q.query(
    `INSERT INTO audit_logs (id, actor_user_id, actor_role, action, target_type, target_id, metadata, ip)
     VALUES ($1, $2, $3, $4, $5, $6, $7, $8)`,
    [newId(), actor ? actor.id : null, actor ? actor.role : null, action, targetType, targetId, JSON.stringify(metadata), ip]
  );
}
